# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#-------------------------------------------------------------------------------------------

# Site's Identification
title: Núcleo de Reparo de Ventiladores Mecânicos
description: Programa voluntário de combate à COVID-19 no estado do Rio de Janeiro.
url: https://rio-covid-19.github.io # the base hostname AND PROTOCOL for your site, e.g. http://example.com
permalink: /:categories/:title

content_type: Informacional #Define whether this is a knowledge base, help center, or something else
use_authors: false #Set this to false to disable showing post authors

brand_logo: logo.png
brand_moto: Juntos contra o COVID-19
header: Núcleo de Reparo de Ventiladores Mecânicos
subheader: Conheça mais sobre a iniciativa e contribua você também!
activity: Atividades
abstract: Mussum Ipsum, cacilds vidis litro abertis. Leite de capivaris, leite de mula manquis sem cabeça. Nullam volutpat risus nec leo commodo, ut interdum diam laoreet. Sed non consequat odio. Quem manda na minha terra sou euzis! Mais vale um bebadis conhecidiss, que um alcoolatra anonimis.

meta_image: odin-meta.png

# Social Links
# twitter_username: 
# facebook_page:
# github_username: 
email: contato@projeto.com
# linkedin_page:
# instagram_username: 


# Navigation
nav_item_one: Sobre
nav_item_one_link: # https://github.com/TeaGuns/odin

nav_item_two: Resultados
nav_item_two_link: # https://twitter.com/TheTeaGuns

nav_item_three: Voluntários
nav_item_three_link: #

nav_button: Contribua
nav_button_link: # https://teaguns.github.io/odin/


# Stakeholders
organization: Organização
funding: Financiamento
partnership: Parceria
support: 
#support: Apoio 

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
